apiVersion: v1
kind: Service
metadata:
  name: kafka-external
  namespace: kafka
  labels:
    app: kafka
spec:
  type: NodePort
  selector:
    app: kafka
  ports:
    - name: broker-outside
      port: 9094
      targetPort: 9094
      nodePort: 30094
