apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-kraft-server-config
  namespace: kafka
data:
  server.properties: |
    process.roles=broker,controller
    controller.listener.names=CONTROLLER
    inter.broker.listener.name=INSIDE
    listener.security.protocol.map=INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT,CONTROLLER:PLAINTEXT
    log.dirs=/kafka/data
    num.partitions=3
    default.replication.factor=1
    min.insync.replicas=1
    offsets.topic.replication.factor=1
    transaction.state.log.replication.factor=1
    transaction.state.log.min.isr=1
    log.retention.hours=168
    log.segment.bytes=1073741824
    log.retention.check.interval.ms=300000
    auto.create.topics.enable=true
